run:
  deadline: 1m

linters:
  enable-all: true
  disable:
    - gocyclo
    - golint
    - unused
    - deadcode
    - structcheck
    - maligned
    - dupl
    - ineffassign
    - interfacer
    - unconvert
    - goconst
    - unparam
    - nakedret
    - lll
    - gochecknoglobals
    - gocritic
    - gochecknoinits
    - godox
    - wsl
    - whitespace
    - funlen
    - gocognit
    - errcheck
