// generated by stringer -type=RetCode; DO NOT EDIT

package types

import "fmt"

const _RetCode_name = "RetCodeOKRetCodeInternalError"

var _RetCode_index = [...]uint8{0, 9, 29}

func (i RetCode) String() string {
	if i < 0 || i >= RetCode(len(_RetCode_index)-1) {
		return fmt.Sprintf("RetCode(%d)", i)
	}
	return _RetCode_name[_RetCode_index[i]:_RetCode_index[i+1]]
}
