// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: proto/proof.proto

package iavl

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// ValueOp is a Protobuf representation of iavl.ValueOp.
type ValueOp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Proof *RangeProof `protobuf:"bytes,1,opt,name=proof,proto3" json:"proof,omitempty"`
}

func (x *ValueOp) Reset() {
	*x = ValueOp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proof_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValueOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueOp) ProtoMessage() {}

func (x *ValueOp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proof_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueOp.ProtoReflect.Descriptor instead.
func (*ValueOp) Descriptor() ([]byte, []int) {
	return file_proto_proof_proto_rawDescGZIP(), []int{0}
}

func (x *ValueOp) GetProof() *RangeProof {
	if x != nil {
		return x.Proof
	}
	return nil
}

// AbsenceOp is a Protobuf representation of iavl.AbsenceOp.
type AbsenceOp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Proof *RangeProof `protobuf:"bytes,1,opt,name=proof,proto3" json:"proof,omitempty"`
}

func (x *AbsenceOp) Reset() {
	*x = AbsenceOp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proof_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AbsenceOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbsenceOp) ProtoMessage() {}

func (x *AbsenceOp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proof_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbsenceOp.ProtoReflect.Descriptor instead.
func (*AbsenceOp) Descriptor() ([]byte, []int) {
	return file_proto_proof_proto_rawDescGZIP(), []int{1}
}

func (x *AbsenceOp) GetProof() *RangeProof {
	if x != nil {
		return x.Proof
	}
	return nil
}

// RangeProof is a Protobuf representation of iavl.RangeProof.
type RangeProof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LeftPath   []*ProofInnerNode `protobuf:"bytes,1,rep,name=left_path,json=leftPath,proto3" json:"left_path,omitempty"`
	InnerNodes []*PathToLeaf     `protobuf:"bytes,2,rep,name=inner_nodes,json=innerNodes,proto3" json:"inner_nodes,omitempty"`
	Leaves     []*ProofLeafNode  `protobuf:"bytes,3,rep,name=leaves,proto3" json:"leaves,omitempty"`
}

func (x *RangeProof) Reset() {
	*x = RangeProof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proof_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RangeProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeProof) ProtoMessage() {}

func (x *RangeProof) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proof_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeProof.ProtoReflect.Descriptor instead.
func (*RangeProof) Descriptor() ([]byte, []int) {
	return file_proto_proof_proto_rawDescGZIP(), []int{2}
}

func (x *RangeProof) GetLeftPath() []*ProofInnerNode {
	if x != nil {
		return x.LeftPath
	}
	return nil
}

func (x *RangeProof) GetInnerNodes() []*PathToLeaf {
	if x != nil {
		return x.InnerNodes
	}
	return nil
}

func (x *RangeProof) GetLeaves() []*ProofLeafNode {
	if x != nil {
		return x.Leaves
	}
	return nil
}

// PathToLeaf is a Protobuf representation of iavl.PathToLeaf.
type PathToLeaf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inners []*ProofInnerNode `protobuf:"bytes,1,rep,name=inners,proto3" json:"inners,omitempty"`
}

func (x *PathToLeaf) Reset() {
	*x = PathToLeaf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proof_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PathToLeaf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathToLeaf) ProtoMessage() {}

func (x *PathToLeaf) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proof_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathToLeaf.ProtoReflect.Descriptor instead.
func (*PathToLeaf) Descriptor() ([]byte, []int) {
	return file_proto_proof_proto_rawDescGZIP(), []int{3}
}

func (x *PathToLeaf) GetInners() []*ProofInnerNode {
	if x != nil {
		return x.Inners
	}
	return nil
}

// ProofInnerNode is a Protobuf representation of iavl.ProofInnerNode.
type ProofInnerNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height  int32  `protobuf:"zigzag32,1,opt,name=height,proto3" json:"height,omitempty"`
	Size    int64  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Version int64  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Left    []byte `protobuf:"bytes,4,opt,name=left,proto3" json:"left,omitempty"`
	Right   []byte `protobuf:"bytes,5,opt,name=right,proto3" json:"right,omitempty"`
}

func (x *ProofInnerNode) Reset() {
	*x = ProofInnerNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proof_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProofInnerNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProofInnerNode) ProtoMessage() {}

func (x *ProofInnerNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proof_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProofInnerNode.ProtoReflect.Descriptor instead.
func (*ProofInnerNode) Descriptor() ([]byte, []int) {
	return file_proto_proof_proto_rawDescGZIP(), []int{4}
}

func (x *ProofInnerNode) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ProofInnerNode) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ProofInnerNode) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ProofInnerNode) GetLeft() []byte {
	if x != nil {
		return x.Left
	}
	return nil
}

func (x *ProofInnerNode) GetRight() []byte {
	if x != nil {
		return x.Right
	}
	return nil
}

// ProofLeafNode is a Protobuf representation of iavl.ProofInnerNode.
type ProofLeafNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key       []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ValueHash []byte `protobuf:"bytes,2,opt,name=value_hash,json=valueHash,proto3" json:"value_hash,omitempty"`
	Version   int64  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *ProofLeafNode) Reset() {
	*x = ProofLeafNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proof_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProofLeafNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProofLeafNode) ProtoMessage() {}

func (x *ProofLeafNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proof_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProofLeafNode.ProtoReflect.Descriptor instead.
func (*ProofLeafNode) Descriptor() ([]byte, []int) {
	return file_proto_proof_proto_rawDescGZIP(), []int{5}
}

func (x *ProofLeafNode) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ProofLeafNode) GetValueHash() []byte {
	if x != nil {
		return x.ValueHash
	}
	return nil
}

func (x *ProofLeafNode) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_proto_proof_proto protoreflect.FileDescriptor

var file_proto_proof_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x69, 0x61, 0x76, 0x6c, 0x22, 0x31, 0x0a, 0x07, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x4f, 0x70, 0x12, 0x26, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x69, 0x61, 0x76, 0x6c, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65,
	0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x22, 0x33, 0x0a, 0x09,
	0x41, 0x62, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x4f, 0x70, 0x12, 0x26, 0x0a, 0x05, 0x70, 0x72, 0x6f,
	0x6f, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x69, 0x61, 0x76, 0x6c, 0x2e,
	0x52, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x6f,
	0x66, 0x22, 0x9f, 0x01, 0x0a, 0x0a, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x72, 0x6f, 0x6f, 0x66,
	0x12, 0x31, 0x0a, 0x09, 0x6c, 0x65, 0x66, 0x74, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x69, 0x61, 0x76, 0x6c, 0x2e, 0x50, 0x72, 0x6f, 0x6f, 0x66,
	0x49, 0x6e, 0x6e, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x08, 0x6c, 0x65, 0x66, 0x74, 0x50,
	0x61, 0x74, 0x68, 0x12, 0x31, 0x0a, 0x0b, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x6e, 0x6f, 0x64,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x69, 0x61, 0x76, 0x6c, 0x2e,
	0x50, 0x61, 0x74, 0x68, 0x54, 0x6f, 0x4c, 0x65, 0x61, 0x66, 0x52, 0x0a, 0x69, 0x6e, 0x6e, 0x65,
	0x72, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x06, 0x6c, 0x65, 0x61, 0x76, 0x65, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x69, 0x61, 0x76, 0x6c, 0x2e, 0x50, 0x72,
	0x6f, 0x6f, 0x66, 0x4c, 0x65, 0x61, 0x66, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x06, 0x6c, 0x65, 0x61,
	0x76, 0x65, 0x73, 0x22, 0x3a, 0x0a, 0x0a, 0x50, 0x61, 0x74, 0x68, 0x54, 0x6f, 0x4c, 0x65, 0x61,
	0x66, 0x12, 0x2c, 0x0a, 0x06, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x69, 0x61, 0x76, 0x6c, 0x2e, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x49, 0x6e,
	0x6e, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x06, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x22,
	0x80, 0x01, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x4e, 0x6f,
	0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x11, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x65, 0x66, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x72, 0x69, 0x67, 0x68, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x72, 0x69, 0x67,
	0x68, 0x74, 0x22, 0x5a, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x4c, 0x65, 0x61, 0x66, 0x4e,
	0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x68,
	0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x48, 0x61, 0x73, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x0c,
	0x5a, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x61, 0x76, 0x6c, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_proof_proto_rawDescOnce sync.Once
	file_proto_proof_proto_rawDescData = file_proto_proof_proto_rawDesc
)

func file_proto_proof_proto_rawDescGZIP() []byte {
	file_proto_proof_proto_rawDescOnce.Do(func() {
		file_proto_proof_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_proof_proto_rawDescData)
	})
	return file_proto_proof_proto_rawDescData
}

var file_proto_proof_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_proof_proto_goTypes = []interface{}{
	(*ValueOp)(nil),        // 0: iavl.ValueOp
	(*AbsenceOp)(nil),      // 1: iavl.AbsenceOp
	(*RangeProof)(nil),     // 2: iavl.RangeProof
	(*PathToLeaf)(nil),     // 3: iavl.PathToLeaf
	(*ProofInnerNode)(nil), // 4: iavl.ProofInnerNode
	(*ProofLeafNode)(nil),  // 5: iavl.ProofLeafNode
}
var file_proto_proof_proto_depIdxs = []int32{
	2, // 0: iavl.ValueOp.proof:type_name -> iavl.RangeProof
	2, // 1: iavl.AbsenceOp.proof:type_name -> iavl.RangeProof
	4, // 2: iavl.RangeProof.left_path:type_name -> iavl.ProofInnerNode
	3, // 3: iavl.RangeProof.inner_nodes:type_name -> iavl.PathToLeaf
	5, // 4: iavl.RangeProof.leaves:type_name -> iavl.ProofLeafNode
	4, // 5: iavl.PathToLeaf.inners:type_name -> iavl.ProofInnerNode
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_proof_proto_init() }
func file_proto_proof_proto_init() {
	if File_proto_proof_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_proof_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValueOp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proof_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AbsenceOp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proof_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RangeProof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proof_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PathToLeaf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proof_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProofInnerNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proof_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProofLeafNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_proof_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_proof_proto_goTypes,
		DependencyIndexes: file_proto_proof_proto_depIdxs,
		MessageInfos:      file_proto_proof_proto_msgTypes,
	}.Build()
	File_proto_proof_proto = out.File
	file_proto_proof_proto_rawDesc = nil
	file_proto_proof_proto_goTypes = nil
	file_proto_proof_proto_depIdxs = nil
}
