name: Benchmarks
on: [push, pull_request]

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.6' # The Go version to download (if necessary) and use.
# This runs only basic benchmarks, and is here so that changes and databases can be compared to each other. 
      - run: make bench

